filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'

build:
  nodes:
    php73:
      environment:
        php:
          version: "7.3"
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

tools:
    external_code_coverage: true
