filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'

build:
  nodes:
    php:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

tools:
    external_code_coverage: true
