language: php

php: ["7.0", "7.1", "7.2", "7.3"]

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

addons:
  apt:
    packages:
      - poppler-utils

env:
  - FULL_BUILD_PHP_VERSION="7.3"

before_script:
  - phpenv config-rm xdebug.ini
  - travis_retry composer install --no-progress --no-interaction --prefer-dist

script:
  - mkdir -p build/tests/
  - vendor/bin/phplint
  - vendor/bin/phpcs -sp bin/ src/ tests/
  - vendor/bin/php-cs-fixer fix --using-cache=no --dry-run --verbose
  - |
    if [[ $TRAVIS_PHP_VERSION == $FULL_BUILD_PHP_VERSION ]]; then
      phpenv config-add xdebug.ini
      vendor/bin/phpunit --coverage-text --coverage-clover=build/tests/coverage.xml
    else
      vendor/bin/phpunit
    fi
  - vendor/bin/phpstan analyse --level max bin/ src/ tests/
  # build phar
  - |
    if [[ $TRAVIS_PHP_VERSION == $FULL_BUILD_PHP_VERSION ]]; then
      bash build-phar
      test -f build/cfditopdf.phar
    fi

after_script:
  # upload test covegare to scrutinizer
  - |
    if [[ $TRAVIS_PHP_VERSION == $FULL_BUILD_PHP_VERSION ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/tests/coverage.xml
    fi

deploy:
  provider: releases
  api_key:
    secure: V++o2L8UWr9GLicxWDnT3JFf+VnbxAAbkd1py8y14ISar7XzgfJ4A06KvwvQz2CYZpeHNeG3fakl4HyFuVl/cU+UxZtMAgMTpQs7d33pTpaFSKT8eOesNJQzRqhLr8PDUy6zAoDz+gNjMs7laQqh4PhK9+DoM2+EReno86pWqo6uWdSrv+PNYmIHObrWkAKJo4eZcmCV+4BnpVKmcuyKqYvXaTfSF3gPqZMsByGYn7jitiVu/9/t004BIlahXh0oTj8dpvNEUyWg2LTIa88PrlI6MFrS9vBs+4FVBrElxZxNWTtY/vj3FkDuxn84Yjn9s3q+6pinbmM4240O95VVU/qhlrdsx0RDAfgxZ+yH7fx8aD9zcrVG7tD7FuwgIbTUEJxTj0TBlQIB7zkxDoIygxvBqLgpPQ+/8TjCsja0fwqmrbfB6t2MtgJtLFBc5tAFaHeKkky5FvrR2fJaDg8WzsFR70pLbTqQ8BXjkiXIMKLV2NxQaPpbvlBis/Jq9oa39zy9W2OQB6OJs+2xPIL46mw3W5ZANpste4sUPdalx2vTA+gOrokEKYvzkoSf0zJAjGpO8D0PEObtc/AOybpfgFcXFQ15HiA4U65tdgOEZwmrRRzm/kAa8TewP3KaYM3BaEZvz9+3XP2bZuHLfJdjhiWmBoxFkC4opiLVAUoQ3N0=
  skip_cleanup: true
  file: build/cfditopdf.phar
  on:
    repo: phpcfdi/cfditopdf
    condition: $TRAVIS_PHP_VERSION == $FULL_BUILD_PHP_VERSION
    tags: true

notifications:
  email: false
